# Generated by Django 4.0.2 on 2022-02-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assesment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='datastream',
        ),
        migrations.RemoveField(
            model_name='data',
            name='timestampe',
        ),
    ]
