# Generated by Django 4.0.2 on 2022-02-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
