# Generated by Django 4.0.2 on 2022-02-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesment', '0002_alter_data_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='datastream',
            field=models.TextField(default='9'),
            preserve_default=False,
        ),
    ]
