# Generated by Django 4.0.2 on 2022-02-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesment', '0002_alter_data_datastream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='timestamp',
            field=models.TimeField(),
        ),
    ]
