# Generated by Django 4.0.2 on 2022-02-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesment', '0002_remove_data_datastream_remove_data_timestampe'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='datastream',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
