# Generated by Django 4.0.2 on 2022-02-20 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assesment', '0003_data_datastream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='datastream',
        ),
    ]
