# Generated by Django 4.0.2 on 2022-02-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesment', '0004_remove_data_datastream'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='timestamp',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
