# Generated by Django 4.0.2 on 2022-02-20 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assesment', '0005_data_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='timestamp',
            new_name='time_stamp',
        ),
    ]
